# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Medtechat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --only=production

      - name: Create deployment package
        run: |
          # Create a clean deployment package
          mkdir deployment-package
          cp -r . deployment-package/
          cd deployment-package
          # Remove unnecessary files for deployment
          rm -rf .git .github node_modules/.cache test-* *.md
          # Reinstall production dependencies
          npm ci --only=production
          cd ..
          tar -czf deployment-package.tar.gz -C deployment-package .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract deployment package
        run: |
          mkdir app
          tar -xzf deployment-package.tar.gz -C app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_11E4A4EEDEF045E395C71EA12E640825 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_987C8C9B0C9E4D95A8868BD353A64AEF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AD2BF8A8896E44B4BB94991CEB13AA73 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Medtechat'
          slot-name: 'Production'
          package: ./app
          